services:
  backend:
    image: 851725206988.dkr.ecr.us-east-1.amazonaws.com/react-express-backend:latest
    ports:
      - "80:80"
    environment:
      DATABASE_DB: example
      DATABASE_USER: root
      DATABASE_PASSWORD: /run/secrets/db-password
      DATABASE_HOST: db
      NODE_ENV: production
    secrets:
      - db-password
    depends_on:
      - db
    networks:
      - public
      - private

  frontend:
    image: 851725206988.dkr.ecr.us-east-1.amazonaws.com/react-express-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - public

  db:
    image: mariadb:10.6.4-focal
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private

networks:
  public:
  private:

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
